# MPLAB IDE generated this makefile for use with GNU make.
# Project: CORDIC.mcp
# Date: Wed Jun 20 14:49:04 2018

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

CORDIC.cof : CORDIC.o
	$(CC) /p18F452 "CORDIC.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"CORDIC.cof" /M"CORDIC.map" /W /x

#CORDIC.o : CORDIC.asm C:/Program\ Files\ (x86)/Microchip/MPASM\ Suite/p18f452.inc
#	$(AS) /q /p18F452 "CORDIC.asm" /l"CORDIC.lst" /e"CORDIC.err" /d__DEBUG=1

clean : 
	$(RM) CORDIC.O CORDIC.HEX CORDIC.err CORDIC.lst CORDIC.cof

